# Goal
float64 spiral_radius
int32 num_points
bool start_outside
float64 num_loops
string pour_frame
geometry_msgs/Quaternion tilt_ang
float64 y_offset
---
# Result
bool status
---
# Feedback
string stage